// ===== CONSTANTS =====
window.CONSTANTS_IT_OBJ = window.CONSTANTS_IT_OBJ || {
    // Page and Application Titles
    PAGE_TITLE: 'Hall of Fame - Classifica Giochi Famiglia',
    APP_TITLE: {
        HALL: 'Hall',
        OF: 'of', 
        FAME: 'Fame'
    },

    // Navigation Labels
    NAVIGATION: {
        PLAYERS: 'Giocatori',
        GAMES: 'Giochi',
        MATCHES: 'Partite'
    },

    // Section Headers
    SECTIONS: {
        RANKING: 'Classifica',
        PLAYERS: 'Giocatori',
        GAMES: 'Giochi',
        MATCHES: 'Partite',
        GAME_RANKING: 'Classifica Gioco'
    },

    // Button Labels
    BUTTONS: {
        ADD_PLAYER: 'Aggiungi Giocatore',
        ADD_GAME: 'Aggiungi Gioco',
        RECORD_MATCH: 'Registra Partita',
        ADD_PARTICIPANT: 'Aggiungi Partecipante',
        CANCEL: 'Annulla',
        ADD: 'Aggiungi',
        SAVE: 'Salva',
        SAVE_CHANGES: 'Salva Modifiche',
        CLOSE: 'Chiudi',
        IMPORT: 'Importa',
        EXPORT: 'Esporta'
    },

    // Form Labels
    FORM_LABELS: {
        NAME: 'Nome',
        GAME_NAME: 'Nome del Gioco',
        AVATAR: 'Avatar',
        GAME: 'Gioco',
        DATE: 'Data',
        TYPE: 'Tipo',
        PARTICIPANTS_AND_RESULTS: 'Partecipanti e Risultati',
        BACKUP_FILE: 'Seleziona file .hof'
    },

    // Form Placeholders and Help Text
    FORM_HELP: {
        AVATAR_FILTER: 'Filtra avatar... (es: \'gatto\', \'felice\', \'cibo\')',
        AVATAR_FILTER_HELP: 'Digita per filtrare la lista degli avatar',
        SELECT_GAME_PLACEHOLDER: 'Seleziona un gioco...',
        BACKUP_FILE_HELP: 'Seleziona un file di backup (.hof) precedentemente esportato'
    },

    // Dropdown Options
    DROPDOWN_OPTIONS: {
        RANKING_SORT: {
            POINTS: 'Per Punteggio',
            PERFORMANCE: 'Per Performance'
        },
        GAME_TYPES: {
            BOARD: 'Gioco da Tavolo',
            CARD: 'Gioco di Carte', 
            GARDEN: 'Gioco da Giardino',
            SPORT: 'Sport',
            OTHER: 'Altro'
        }
    },

    // Modal Titles
    MODAL_TITLES: {
        ADD_PLAYER: 'Aggiungi Giocatore',
        EDIT_PLAYER: 'Modifica Giocatore',
        ADD_GAME: 'Aggiungi Gioco',
        EDIT_GAME: 'Modifica Gioco',
        RECORD_MATCH: 'Registra Partita',
        IMPORT_BACKUP: 'Importa Backup',
        GAME_RANKING: 'Classifica Gioco'
    },

    // Alert Messages
    ALERTS: {
        IMPORT_WARNING_TITLE: 'Attenzione!',
        IMPORT_WARNING_MESSAGE: 'L\'importazione sostituirà tutti i dati attuali (giocatori, giochi e partite) con quelli del file di backup.'
    },

    // Footer and Links
    FOOTER: {
        BACKUP: 'Backup',
        EXPORT_BACKUP: 'Esporta Backup (.hof)',
        IMPORT_BACKUP: 'Importa Backup',
        GITHUB_TITLE: 'View on GitHub',
        SETTINGS: 'Impostazioni',
        LANGUAGE: 'Lingua',
        ITALIAN: 'Italiano',
        ENGLISH: 'English'
    },

    // Additional UI Text
    UI_TEXT: {
        PARTITA: 'partita',
        PARTITE: 'partite',
        PARTITE_GIOCATE: 'Partite giocate',
        CLASSIFICA: 'Classifica',
        PRIMO_POSTO: 'Primo posto',
        ULTIMO_POSTO: 'Ultimo posto',
        ELIMINA: 'Elimina',
        MODIFICA: 'Modifica',
        NESSUN_GIOCATORE_CLASSIFICA: 'Nessun giocatore in classifica',
        NESSUNA_PARTITA: 'Nessuna partita registrata. Inizia registrando le prime partite!',
        AGGIUNGI_PARTITE_CLASSIFICA: 'Aggiungi i giocatori, i giochi e registra le prime partite per vedere la classifica',
        GIOCO_ELIMINATO: 'Gioco eliminato',
        GIOCATORE_ELIMINATO: 'Giocatore eliminato',
        PODIO_CLASSIFICA_PUNTEGGI: 'Podio nella classifica dei punteggi completa',
        PRIMO_POSTO_GIOCO: 'Primo posto a',
        SECONDO_POSTO: 'Secondo posto',
        TERZO_POSTO: 'Terzo posto',
        MIGLIOR_PERFORMANCE: 'Miglior performance'
    },

    // Avatar Categories and Labels
    AVATAR_CATEGORIES: {
        FACES_EMOTIONS: {
            SORRIDENTE: 'Sorridente',
            COOL: 'Cool',
            STELLARE: 'Stellare',
            FESTA: 'Festa',
            WOW: 'Wow',
            INNAMORATO: 'Innamorato',
            PENSIEROSO: 'Pensieroso',
            FELICE: 'Felice',
            LACRIME: 'Lacrime',
            AMOROSO: 'Amoroso',
            ANGELO: 'Angelo',
            ABBRACCIO: 'Abbraccio',
            TIMIDO: 'Timido',
            SILENZIO: 'Silenzio',
            SOSPETTOSO: 'Sospettoso',
            FURBO: 'Furbo',
            DORMIENTE: 'Dormiente',
            NERD: 'Nerd',
            FREDDO: 'Freddo',
            CALDO: 'Caldo',
            MISTERIOSO: 'Misterioso',
            PAZZO: 'Pazzo',
            STORDITO: 'Stordito',
            SOLDI: 'Soldi',
            COWBOY: 'Cowboy'
        },
        PEOPLE: {
            BIMBO: 'Bimbo',
            BIMBO_CHIARO: 'Bimbo Chiaro',
            BIMBO_MEDIO_CHIARO: 'Bimbo Medio-Chiaro',
            BIMBO_MEDIO: 'Bimbo Medio',
            BIMBO_MEDIO_SCURO: 'Bimbo Medio-Scuro',
            BIMBO_SCURO: 'Bimbo Scuro',
            BIMBA: 'Bimba',
            BIMBA_CHIARA: 'Bimba Chiara',
            BIMBA_MEDIO_CHIARA: 'Bimba Medio-Chiara',
            BIMBA_MEDIA: 'Bimba Media',
            BIMBA_MEDIO_SCURA: 'Bimba Medio-Scura',
            BIMBA_SCURA: 'Bimba Scura',
            BAMBINO: 'Bambino',
            BAMBINO_CHIARO: 'Bambino Chiaro',
            BAMBINO_MEDIO_CHIARO: 'Bambino Medio-Chiaro',
            BAMBINO_MEDIO: 'Bambino Medio',
            BAMBINO_MEDIO_SCURO: 'Bambino Medio-Scuro',
            BAMBINO_SCURO: 'Bambino Scuro',
            DONNA: 'Donna',
            DONNA_CHIARA: 'Donna Chiara',
            DONNA_MEDIO_CHIARA: 'Donna Medio-Chiara',
            DONNA_MEDIA: 'Donna Media',
            DONNA_MEDIO_SCURA: 'Donna Medio-Scura',
            DONNA_SCURA: 'Donna Scura',
            DONNA_BIONDA: 'Donna Bionda',
            DONNA_BIONDA_CHIARA: 'Donna Bionda Chiara',
            DONNA_BIONDA_MEDIO_CHIARA: 'Donna Bionda Medio-Chiara',
            DONNA_BIONDA_MEDIA: 'Donna Bionda Media',
            DONNA_BIONDA_MEDIO_SCURA: 'Donna Bionda Medio-Scura',
            DONNA_BIONDA_SCURA: 'Donna Bionda Scura',
            DONNA_RICCIA: 'Donna Riccia',
            DONNA_RICCIA_CHIARA: 'Donna Riccia Chiara',
            DONNA_RICCIA_MEDIO_CHIARA: 'Donna Riccia Medio-Chiara',
            DONNA_RICCIA_MEDIA: 'Donna Riccia Media',
            DONNA_RICCIA_MEDIO_SCURA: 'Donna Riccia Medio-Scura',
            DONNA_RICCIA_SCURA: 'Donna Riccia Scura',
            DONNA_ROSSA: 'Donna Rossa',
            DONNA_ROSSA_CHIARA: 'Donna Rossa Chiara',
            DONNA_ROSSA_MEDIO_CHIARA: 'Donna Rossa Medio-Chiara',
            DONNA_ROSSA_MEDIA: 'Donna Rossa Media',
            DONNA_ROSSA_MEDIO_SCURA: 'Donna Rossa Medio-Scura',
            DONNA_ROSSA_SCURA: 'Donna Rossa Scura',
            DONNA_BIANCA: 'Donna Bianca',
            DONNA_BIANCA_CHIARA: 'Donna Bianca Chiara',
            DONNA_BIANCA_MEDIO_CHIARA: 'Donna Bianca Medio-Chiara',
            DONNA_BIANCA_MEDIA: 'Donna Bianca Media',
            DONNA_BIANCA_MEDIO_SCURA: 'Donna Bianca Medio-Scura',
            DONNA_BIANCA_SCURA: 'Donna Bianca Scura',
            DONNA_CALVA: 'Donna Calva',
            DONNA_CALVA_CHIARA: 'Donna Calva Chiara',
            DONNA_CALVA_MEDIO_CHIARA: 'Donna Calva Medio-Chiara',
            DONNA_CALVA_MEDIA: 'Donna Calva Media',
            DONNA_CALVA_MEDIO_SCURA: 'Donna Calva Medio-Scura',
            DONNA_CALVA_SCURA: 'Donna Calva Scura',
            UOMO: 'Uomo',
            UOMO_CHIARO: 'Uomo Chiaro',
            UOMO_MEDIO_CHIARO: 'Uomo Medio-Chiaro',
            UOMO_MEDIO: 'Uomo Medio',
            UOMO_MEDIO_SCURO: 'Uomo Medio-Scuro',
            UOMO_SCURO: 'Uomo Scuro',
            UOMO_BIONDO: 'Uomo Biondo',
            UOMO_BIONDO_CHIARO: 'Uomo Biondo Chiaro',
            UOMO_BIONDO_MEDIO_CHIARO: 'Uomo Biondo Medio-Chiaro',
            UOMO_BIONDO_MEDIO: 'Uomo Biondo Medio',
            UOMO_BIONDO_MEDIO_SCURO: 'Uomo Biondo Medio-Scuro',
            UOMO_BIONDO_SCURO: 'Uomo Biondo Scuro',
            UOMO_RICCIO: 'Uomo Riccio',
            UOMO_RICCIO_CHIARO: 'Uomo Riccio Chiaro',
            UOMO_RICCIO_MEDIO_CHIARO: 'Uomo Riccio Medio-Chiaro',
            UOMO_RICCIO_MEDIO: 'Uomo Riccio Medio',
            UOMO_RICCIO_MEDIO_SCURO: 'Uomo Riccio Medio-Scuro',
            UOMO_RICCIO_SCURO: 'Uomo Riccio Scuro',
            UOMO_ROSSO: 'Uomo Rosso',
            UOMO_ROSSO_CHIARO: 'Uomo Rosso Chiaro',
            UOMO_ROSSO_MEDIO_CHIARO: 'Uomo Rosso Medio-Chiaro',
            UOMO_ROSSO_MEDIO: 'Uomo Rosso Medio',
            UOMO_ROSSO_MEDIO_SCURO: 'Uomo Rosso Medio-Scuro',
            UOMO_ROSSO_SCURO: 'Uomo Rosso Scuro',
            UOMO_BIANCO: 'Uomo Bianco',
            UOMO_BIANCO_CHIARO: 'Uomo Bianco Chiaro',
            UOMO_BIANCO_MEDIO_CHIARO: 'Uomo Bianco Medio-Chiaro',
            UOMO_BIANCO_MEDIO: 'Uomo Bianco Medio',
            UOMO_BIANCO_MEDIO_SCURO: 'Uomo Bianco Medio-Scuro',
            UOMO_BIANCO_SCURO: 'Uomo Bianco Scuro',
            UOMO_CALVO: 'Uomo Calvo',
            UOMO_CALVO_CHIARO: 'Uomo Calvo Chiaro',
            UOMO_CALVO_MEDIO_CHIARO: 'Uomo Calvo Medio-Chiaro',
            UOMO_CALVO_MEDIO: 'Uomo Calvo Medio',
            UOMO_CALVO_MEDIO_SCURO: 'Uomo Calvo Medio-Scuro',
            UOMO_CALVO_SCURO: 'Uomo Calvo Scuro',
            NONNA: 'Nonna',
            NONNA_CHIARA: 'Nonna Chiara',
            NONNA_MEDIO_CHIARA: 'Nonna Medio-Chiara',
            NONNA_MEDIA: 'Nonna Media',
            NONNA_MEDIO_SCURA: 'Nonna Medio-Scura',
            NONNA_SCURA: 'Nonna Scura',
            NONNO: 'Nonno',
            NONNO_CHIARO: 'Nonno Chiaro',
            NONNO_MEDIO_CHIARO: 'Nonno Medio-Chiaro',
            NONNO_MEDIO: 'Nonno Medio',
            NONNO_MEDIO_SCURO: 'Nonno Medio-Scuro',
            NONNO_SCURO: 'Nonno Scuro'
        },
        PROFESSIONS: {
            POLIZIOTTA: 'Poliziotta',
            POLIZIOTTO: 'Poliziotto',
            COSTRUTTRICE: 'Costruttrice',
            COSTRUTTORE: 'Costruttore',
            GUARDIA: 'Guardia',
            DETECTIVE: 'Detective',
            DOTTORESSA: 'Dottoressa',
            DOTTORE: 'Dottore',
            CONTADINA: 'Contadina',
            CONTADINO: 'Contadino',
            CHEF: 'Chef',
            STUDENTESSA: 'Studentessa',
            STUDENTE: 'Studente',
            CANTANTE: 'Cantante',
            INSEGNANTE: 'Insegnante',
            PROGRAMMATRICE: 'Programmatrice',
            PROGRAMMATORE: 'Programmatore',
            ASTRONAUTA: 'Astronauta',
            POMPIERE: 'Pompiere',
            NINJA: 'Ninja',
            PRINCIPE: 'Principe',
            PRINCIPESSA: 'Principessa'
        },
        FANTASY_CHARACTERS: {
            FANTASMA: 'Fantasma',
            PAGLIACCIO: 'Pagliaccio',
            OGRE: 'Ogre',
            GOBLIN: 'Goblin',
            ROBOT: 'Robot',
            ALIENO: 'Alieno',
            MOSTRO: 'Mostro',
            BABBO_NATALE: 'Babbo Natale',
            MAMMA_NATALE: 'Mamma Natale',
            STREGA: 'Strega',
            MAGO: 'Mago',
            FATA: 'Fata',
            FOLLETTO: 'Folletto',
            VAMPIRA: 'Vampira',
            VAMPIRO: 'Vampiro',
            ZOMBIE: 'Zombie'
        },
        ANIMALS: {
            CANE: 'Cane',
            GATTO: 'Gatto',
            TOPO: 'Topo',
            CRICETO: 'Criceto',
            CONIGLIO: 'Coniglio',
            VOLPE: 'Volpe',
            ORSO: 'Orso',
            PANDA: 'Panda',
            KOALA: 'Koala',
            TIGRE: 'Tigre',
            LEONE: 'Leone',
            MUCCA: 'Mucca',
            MAIALE: 'Maiale',
            RANA: 'Rana',
            SCIMMIA: 'Scimmia',
            NON_VEDO: 'Non Vedo',
            NON_SENTO: 'Non Sento',
            NON_PARLO: 'Non Parlo',
            UNICORNO: 'Unicorno',
            APE: 'Ape',
            BRUCO: 'Bruco',
            FARFALLA: 'Farfalla',
            LUMACA: 'Lumaca',
            COCCINELLA: 'Coccinella',
            FORMICA: 'Formica',
            GRILLO: 'Grillo',
            RAGNO: 'Ragno',
            SCORPIONE: 'Scorpione',
            TARTARUGA: 'Tartaruga',
            SERPENTE: 'Serpente',
            LUCERTOLA: 'Lucertola',
            T_REX: 'T-Rex',
            DINOSAURO: 'Dinosauro',
            POLPO: 'Polpo',
            CALAMARO: 'Calamaro',
            GAMBERO: 'Gambero',
            GRANCHIO: 'Granchio',
            PESCE_PALLA: 'Pesce Palla',
            PESCE: 'Pesce',
            DELFINO: 'Delfino',
            BALENA: 'Balena',
            SQUALO: 'Squalo',
            COCCODRILLO: 'Coccodrillo',
            ZEBRA: 'Zebra',
            GORILLA: 'Gorilla',
            ORANGUTAN: 'Orangutan',
            ELEFANTE: 'Elefante',
            LEOPARDO: 'Leopardo',
            IPPOPOTAMO: 'Ippopotamo',
            RINOCERONTE: 'Rinoceronte',
            CAMMELLO: 'Cammello',
            DROMEDARIO: 'Dromedario',
            GIRAFFA: 'Giraffa',
            CANGURO: 'Canguro',
            BUFALO: 'Bufalo',
            TORO: 'Toro',
            CAVALLO: 'Cavallo',
            ARIETE: 'Ariete',
            PECORA: 'Pecora',
            LAMA: 'Lama',
            CAPRA: 'Capra',
            CERVO: 'Cervo',
            BARBONCINO: 'Barboncino',
            CANE_GUIDA: 'Cane Guida',
            CANE_SERVIZIO: 'Cane Servizio',
            GATTO_NERO: 'Gatto Nero',
            GALLO: 'Gallo',
            GALLINA: 'Gallina',
            PULCINO: 'Pulcino',
            ANATRA: 'Anatra',
            CIGNO: 'Cigno',
            AQUILA: 'Aquila',
            GUFO: 'Gufo',
            PAVONE: 'Pavone',
            PAPPAGALLO: 'Pappagallo',
            OCA: 'Oca',
            PINGUINO: 'Pinguino',
            COLOMBA: 'Colomba',
            PIPISTRELLO: 'Pipistrello',
            LUPO: 'Lupo',
            RICCIO: 'Riccio',
            PROCIONE: 'Procione',
            SCOIATTOLO: 'Scoiattolo'
        },
        FOOD_DRINKS: {
            MELA: 'Mela',
            ARANCIA: 'Arancia',
            BANANA: 'Banana',
            FRAGOLA: 'Fragola',
            MIRTILLI: 'Mirtilli',
            UVA: 'Uva',
            KIWI: 'Kiwi',
            ANGURIA: 'Anguria',
            CILIEGIE: 'Ciliegie',
            CILIEGIA: 'Ciliegia',
            MANGO: 'Mango',
            ANANAS: 'Ananas',
            COCCO: 'Cocco',
            CAROTA: 'Carota',
            PEPERONCINO: 'Peperoncino',
            OLIVA: 'Oliva',
            AVOCADO: 'Avocado',
            MELANZANA: 'Melanzana',
            PATATA: 'Patata',
            BAGUETTE: 'Baguette',
            BAGEL: 'Bagel',
            FORMAGGIO: 'Formaggio',
            CARNE: 'Carne',
            BACON: 'Bacon',
            HAMBURGER: 'Hamburger',
            PATATINE: 'Patatine',
            PIZZA: 'Pizza',
            HOT_DOG: 'Hot Dog',
            SANDWICH: 'Sandwich',
            TACO: 'Taco',
            BURRITO: 'Burrito',
            INSALATA: 'Insalata',
            RAMEN: 'Ramen',
            PASTA: 'Pasta',
            STUFATO: 'Stufato',
            CURRY: 'Curry',
            SUSHI: 'Sushi',
            GAMBERO: 'Gambero',
            TORTA: 'Torta',
            CUPCAKE: 'Cupcake',
            LECCA_LECCA: 'Lecca-lecca',
            CARAMELLA: 'Caramella',
            CIOCCOLATO: 'Cioccolato',
            DONUT: 'Donut',
            BISCOTTO: 'Biscotto',
            LATTE: 'Latte',
            CAFFE: 'Caffè',
            SUCCO: 'Succo',
            BIBITA: 'Bibita',
            BUBBLE_TEA: 'Bubble Tea',
            BIRRA: 'Birra',
            VINO: 'Vino',
            COCKTAIL: 'Cocktail',
            DRINK: 'Drink',
            WHISKY: 'Whisky'
        },
        OBJECTS_SYMBOLS: {
            CACCA: 'Cacca',
            STELLA: 'Stella',
            STELLA_BRILLANTE: 'Stella Brillante',
            BRILLANTINI: 'Brillantini',
            COMETA: 'Cometa',
            FUOCO: 'Fuoco',
            FULMINE: 'Fulmine',
            DIAMANTE: 'Diamante',
            CORONA: 'Corona',
            BERSAGLIO: 'Bersaglio',
            DADO: 'Dado',
            GAMING: 'Gaming',
            JOYSTICK: 'Joystick',
            TEATRO: 'Teatro',
            CIRCO: 'Circo',
            ARTE: 'Arte',
            CINEMA: 'Cinema',
            MICROFONO: 'Microfono',
            CUFFIE: 'Cuffie',
            MUSICA: 'Musica',
            NOTE: 'Note',
            CHITARRA: 'Chitarra',
            TAMBURO: 'Tamburo',
            TROMBA: 'Tromba',
            SAX: 'Sax',
            RAZZO: 'Razzo',
            UFO: 'UFO',
            ARCOBALENO: 'Arcobaleno',
            PALLONCINO: 'Palloncino',
            FESTA: 'Festa',
            CORIANDOLI: 'Coriandoli',
            REGALO: 'Regalo',
            FIOCCO: 'Fiocco',
            DONO: 'Dono',
            CUORE_ROSA: 'Cuore Rosa',
            DUE_CUORI: 'Due Cuori',
            CUORE_CRESCENTE: 'Cuore Crescente',
            CUORE_BATTENTE: 'Cuore Battente',
            CUPIDO: 'Cupido',
            CUORE_ROSSO: 'Cuore Rosso',
            CUORE_ARANCIONE: 'Cuore Arancione',
            CUORE_GIALLO: 'Cuore Giallo',
            CUORE_VERDE: 'Cuore Verde',
            CUORE_BLU: 'Cuore Blu',
            CUORE_VIOLA: 'Cuore Viola',
            CUORE_NERO: 'Cuore Nero',
            CUORE_BIANCO: 'Cuore Bianco',
            CUORE_MARRONE: 'Cuore Marrone'
        }
    },

    // Existing message constants
    MESSAGES: {
        EMPTY_NAME: 'Inserisci il nome del {type}',
        DUPLICATE_NAME: 'Esiste già un {type} con questo nome',
        CONFIRM_DELETE_PLAYER: 'Sei sicuro di voler eliminare questo giocatore? Tutte le sue partite verranno rimosse.',
        CONFIRM_DELETE_GAME: 'Sei sicuro di voler eliminare questo gioco? Tutte le partite associate verranno rimosse.',
        CONFIRM_DELETE_MATCH: 'Sei sicuro di voler eliminare questa partita?',
        MIN_PLAYERS_FOR_MATCH: 'Aggiungi almeno 2 giocatori prima di registrare una partita',
        MIN_GAMES_FOR_MATCH: 'Aggiungi almeno un gioco prima di registrare una partita',
        SELECT_GAME: 'Seleziona un gioco',
        SELECT_DATE: 'Seleziona una data',
        COMPLETE_PARTICIPANTS: 'Completa tutti i dati dei partecipanti',
        NO_DUPLICATE_PLAYERS: 'Un giocatore non può partecipare due volte alla stessa partita',
        MIN_PARTICIPANTS: 'Servono almeno 2 partecipanti',
        BACKUP_EXPORT_SUCCESS: 'Backup esportato con successo!',
        BACKUP_SELECT_FILE: 'Seleziona un file di backup (.hof)',
        BACKUP_INVALID_FILE: 'Il file selezionato non è un file di backup valido (.hof)',
        BACKUP_IMPORT_SUCCESS: 'Backup importato con successo!',
        BACKUP_EXPORT_ERROR: 'Errore durante l\'esportazione del backup.'
    },

    // Modal types configuration
    MODAL_TYPES: {
        PLAYER: {
            name: 'giocatore',
            addTitle: 'Aggiungi Giocatore',
            editTitle: 'Modifica Giocatore',
            addButton: 'Aggiungi',
            editButton: 'Salva Modifiche'
        },
        GAME: {
            name: 'gioco',
            addTitle: 'Aggiungi Gioco',
            editTitle: 'Modifica Gioco',
            addButton: 'Aggiungi',
            editButton: 'Salva Modifiche'
        }
    },

    // Game mechanics constants
    POSITION_POINTS: {
        winner: 2,
        participant: 1,
        last: 0
    },

    GAME_TYPE_LABELS: {
        board: 'Gioco da Tavolo',
        card: 'Gioco di Carte',
        garden: 'Gioco da Giardino',
        sport: 'Sport',
        other: 'Altro'
    },

    POSITION_LABELS: {
        winner: '🏆 Vittoria',
        participant: '🥈 Piazzamento', 
        last: '😞 Ultimo posto'
    },

    POSITION_BADGE_CLASSES: {
        winner: 'bg-warning',
        participant: 'bg-primary',
        last: 'bg-secondary'
    },

    // Utility methods for text management
    getText(path) {
        return path.split('.').reduce((obj, key) => obj && obj[key], this);
    },

    setText(element, path) {
        const text = this.getText(path);
        if (text && element) {
            element.textContent = text;
        }
        return text;
    },

    setInnerHTML(element, path, icon = null) {
        const text = this.getText(path);
        if (text && element) {
            if (icon) {
                element.innerHTML = `<i class="${icon}"></i>${text}`;
            } else {
                element.innerHTML = text;
            }
        }
        return text;
    }
}; 